### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ssdanso**
added margin-top on screens smaller than width-767px to correct hidden sides on landing page

### CODE REVIEW

**Comment by mercyinyang** [comment]
I do not know what you did. I cannot merge your PR. No hosted link for testing

**Comment by ssdanso** [comment]
> I do not know what you did. I cannot merge your PR. No hosted link for testing

well, just check the hosted link of docufix.ga and check the margin to the top or from the top and you will notice the Document Comparison Solution text has Document a bit hidden. I just added a margin to top media query css line. I didn't see how necessary it is for me to host just that and moreover, unless you view on a smart phone or a device with screen less than 700px in width, you will not notice what i am talking about

**Comment by ssdanso** [comment]
image
this is how it currently looks like

**Comment by ssdanso** [comment]
image
and this is what i did to that......

**Comment by ssdanso** [comment]
image
and this is what i did to that......

**Comment by mercyinyang** [comment]
Your repo is not up to date. Please update your forked repo and push your files again

**Pull request merged**
